version: "3.3"

services:
  telegraf:
    image: telegraf
    networks:
      - tick-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: telegraf-config
        target: /etc/telegraf/telegraf.conf
    deploy:
      restart_policy:
        condition: on-failure
      mode: global
    depends_on: 
      - influxdb

  influxdb:
    image: influxdb
    networks:
      - tick-net
    ports:
      - "8086:8086"
    configs:
      - source: kapacitor-config
        target: /etc/kapacitor/kapacitor.conf
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  chronograf:
    image: chronograf
    networks:
      - tick-net
    ports:
      - "8888:8888"
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    depends_on: 
      - kapacitor
      - influxdb

  kapacitor:
    image: kapacitor
    networks:
      - tick-net
    configs:
      - source: kapacitor-config
        target: /etc/kapacitor/kapacitor.conf
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    ports:
      - "9092:9092"
    depends_on: 
      - influxdb

configs:
  telegraf-config:
    file: $PWD/conf/telegraf/telegraf.conf
  kapacitor-config:
    file: $PWD/conf/kapacitor/kapacitor.conf
  influx-config:
    file: $PWD/conf/influx/influx.conf

networks:
  tick-net:
#driver: overlay