version: "3.3"

services:
  telegraf:
    image: telegraf:1.3
    networks:
      - tick-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: telegraf-config
        target: /etc/telegraf/telegraf.conf
    deploy:
      restart_policy:
        condition: on-failure
      mode: global

  influxdb:
    image: influxdb
    networks:
      - tick-net
    ports:
      - 8086:8086
    configs:
      - source: kapacitor-config
        target: /etc/kapacitor/kapacitor.conf
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  chronograf:
    image: chronograf:1.3
    networks:
      - tick-net
    ports:
      - 8888:8888
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  kapacitor:
    image: kapacitor:1.2
    networks:
      - tick-net
    configs:
      - source: kapacitor-config
        target: /etc/kapacitor/kapacitor.conf
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker

configs:
  telegraf-config:
    file: $PWD/conf/telegraf/telegraf.conf
  kapacitor-config:
    file: $PWD/conf/kapacitor/kapacitor.conf
  influx-config:
    file: $PWD/conf/influx/influx.conf

networks:
  tick-net:
#driver: overlay